http:
  routers:
    api:
      rule: Host(`pw.aklildr.com`) && PathPrefix(`/api`)
      entryPoints:
        - websecure
      service: api
      priority: 100
      tls:
        certResolver: letsencrypt
    socket:
      rule: Host(`pw.aklildr.com`) && PathPrefix(`/socket.io`)
      entryPoints:
        - websecure
      service: api
      priority: 100
      tls:
        certResolver: letsencrypt
    frontend:
      rule: Host(`pw.aklildr.com`)
      entryPoints:
        - websecure
      service: frontend
      priority: 1
      tls:
        certResolver: letsencrypt

  services:
    api:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8081
    frontend:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8082
